### ISSUE TITLE
Unhandled ECONNRESET Error

### ISSUE THREAD

**Issue by espenjutte** [Stefan-Code/peer-harvest#10]
After a while i get the error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write ECONNRESET
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

Seems like some client droping the TCP-connection forcefully and we are not handling the error correctly.

**Comment by Stefan-Code** [comment]
Oh yeah, I know that one. I got it once but was never able to reproduce it. (Even with disconnecting Internet while running.)
It is caused by the bittorrent-swarm library if I recall correctly. However I already added the .on('error', ...); handlers (without effect if you get that error...) so I have to think about a way to solve that...

**Comment by Stefan-Code** [comment]
Is that all the Information you get? (Especially the stacktrace.) It should mention some more files in node_modules. Could you post that too please

**Comment by espenjutte** [comment]
I'l check when i get the error again, been testing a bit so it's sadly gone in the scroll back of my terminal for now.

**Comment by Stefan-Code** [comment]
Ok, thanks.

**Comment by Stefan-Code** [comment]
When testing, please use the 'dev' branch and set the `--dev` switch. That will give you more information on an uncaught error.
